### PR TITLE
Makefile: First try at rewriting the ccan Makefile.

### PR DESCRIPTION
**Pull request by jgriffiths**
This change contains a simpler Makefile replacement with only 62 lines
of directives, 10 rules, and a 13 line support script for dependencies. The
build dependencies have been minimised and in some cases, corrected.

FEATURES:
- All targets can be built from a clean tree in one invocation.
- Parallel builds (tested with -j32 on 8 cores).
- Auto discovery of modules via _info files.
- Hopefully complete dependencies via a simplified generator.
- CFLAGS are respected and appended to compile flags.
- LINTFLAGS can be set to add check options (e.g. LINTFLAGS=-v).
- 'make clean' doesn't build anything before cleaning now.
- 'make quiet=1' builds quietly. 'make check quiet=1 -j N' produces
  summary output like the former summary target.
- Non-phony test targets; tests are rebuilt only when dirty. Targets are:
  check, fastcheck and fullcheck, the latter runs in non-summary mode.
- 'make <module>.[check|fastcheck|fullcheck]' runs tests for single modules.

TODO:
- Support Makefile-web and any other scattered targets

NOTES:
- The changes to dependency generation expose a circular
  dependency between asort and order which is not fixed here.
- Tests always run their dependent tests. With -j support and
  minimised rebuilds via tighter dependencies, its not worth avoiding.
- Some targets have been dropped as uneeded (e.g. distclean, tools).

Signed-off-by: Jon Griffiths jon_p_griffiths@yahoo.com

### CODE REVIEW

**Comment by jgriffiths** [comment]
PR for review. If the approach is OK I will add the Makefile-web support along the same lines.

**Comment by dgibson** [comment]
On Thu, Sep 15, 2016 at 06:49:30PM -0700, jgriffiths wrote:
> This change contains a simpler Makefile replacement with only 62 lines
> of directives, 10 rules, and a 13 line support script for dependencies. The
> build dependencies have been minimised and in some cases, corrected.
> 
> FEATURES:
> * All targets can be built from a clean tree in one invocation.
> * Parallel builds (tested with -j32 on 8 cores).
> * Auto discovery of modules via _info files.
> * Hopefully complete dependencies via a simplified generator.
> * CFLAGS are respected and appended to compile flags.
> * LINTFLAGS can be set to add check options (e.g. LINTFLAGS=-v).
> * 'make clean' doesn't build anything before cleaning now.
> * 'make quiet=1' builds quietly. 'make check quiet=1 -j N' produces
>   summary output like the former summary target.
> * Non-phony test targets; tests are rebuilt only when dirty. Targets are:
>   check, fastcheck and fullcheck, the latter runs in non-summary mode.
> * 'make <module>.[check|fastcheck|fullcheck]' runs tests for single modules.
> 
> TODO:
> * Support Makefile-web and any other scattered targets
> 
> NOTES:
> * The changes to dependency generation expose a circular
>   dependency between asort and order which is not fixed here.
> * Tests always run their dependent tests. With -j support and
>   minimised rebuilds via tighter dependencies, its not worth avoiding.
> * Some targets have been dropped as uneeded (e.g. distclean, tools).
> 
> Signed-off-by: Jon Griffiths <jon_p_griffiths@yahoo.com>
> You can view, comment on, or merge this pull request online at:

Ah, nice to see some work here.  The Makefile at present is pretty
awful.  I've made some baby steps at cleanup, but didn't get very far.

Couple of buglets I noticed:
  - make clean doesn't remove the compiled info files
  - make config.h builds all the info files, then tells me config.h is
    up to date

It definitely looks like an improvement over the current Makefile.

However, it still has the problem that the Makefile and ccanlint use
completely different paths for compiling the modules.  I think that's
asking for trouble - and it already means that ccanlint won't
correctlt build modules that have non-trivial local Makefiles
(e.g. ntdb).

I'm not really sure how to fix that, but I think we need to do have a
sane build model.


> 
>   https://github.com/rustyrussell/ccan/pull/53
> 
> -- Commit Summary --
> 
>   * Makefile: First try at rewriting the ccan Makefile.
> 
> -- File Changes --
> 
>     M .gitignore (8)
>     M Makefile (191)
>     D Makefile-ccan (160)
>     D tools/Makefile (50)
>     D tools/ccanlint/Makefile (50)
>     A tools/gen_deps.sh (27)
> 
> -- Patch Links --
> 
> https://github.com/rustyrussell/ccan/pull/53.patch
> https://github.com/rustyrussell/ccan/pull/53.diff
> 

-- 
David Gibson			| I'll have my music baroque, and my code
david AT gibson.dropbear.id.au	| minimalist, thank you.  NOT _the_ _other_
				| _way_ _around_!
http://www.ozlabs.org/~dgibson

**Comment by jgriffiths** [comment]
@dgibson Thanks for reviewing/testing!

I've fixed the cleaning of info files in this latest push. Building config.h (or anything else except 'clean') causes the info files to be built because they are needed to generate the dependencies included by the makefile. I can add a special case for config.h to avoid reading the dependencies if its the only target, but I'm not sure its worth it as this target is the only one that could use it other than clean (which is more commonly I suspect). Let me know if you disagree and I'll add it.

> I'm not really sure how to fix that, but I think we need to do have a
> sane build model.

I agree. This change is meant to leave things similar to how they stand but be more easy to improve in the future. For example, supporting out of tree builds/tests will be trivial with this impl and would support e.g. testing debug and optimised together with travis.

Regarding the windows changes, I wrote a wrapper for the command line msvc tools using wine that converts gcc options and unix paths to call the ms compiler and linker running under wine. This would allow us to build and test the windows builds on linux boxes (ignoring any wine bugs of course). I will try to find it this weekend and put it up under my github account. for you to have a look at if you are interested.

Otherwise I think rather than have the build commands in more than one place, the Makefile should generate wrapper scripts to call the compiler/linker with the correct options/paths, that ccanlint can use instead of directly calling the tools itself. In that case its just a matter of detecting windows in the Makefile which is fairly easy given gnu make on the windows box.

**Comment by dgibson** [comment]
On Tue, Sep 20, 2016 at 06:45:37PM -0700, jgriffiths wrote:
> @dgibson Thanks for reviewing/testing!
> 
> I've fixed the cleaning of info files in this latest push. Building
> config.h (or anything else except 'clean') causes the info files to
> be built because they are needed to generate the dependencies
> included by the makefile. I can add a special case for config.h to
> avoid reading the dependencies if its the only target, but I'm not
> sure its worth it as this target is the only one that could use it
> other than clean (which is more commonly I suspect). Let me know if
> you disagree and I'll add it.

I disagree :).  I think it's worth having the special case for this.
make config.h is a typical target when you just need minimal setup to
then start working with ccanlint.  Given the problems with make
vs. ccanlint building, that's a pretty reasonable thing to do at this
point.

> > I'm not really sure how to fix that, but I think we need to do have a
> > sane build model.
> 
> I agree. This change is meant to leave things similar to how they
> stand but be more easy to improve in the future. For example,
> supporting out of tree builds/tests will be trivial with this impl
> and would support e.g. testing debug and optimised together with
> travis.

Ok, makes sense to me.

> Regarding the windows changes, I wrote a wrapper for the command
> line msvc tools using wine that converts gcc options and unix paths
> to call the ms compiler and linker running under wine. This would
> allow us to build and test the windows builds on linux boxes
> (ignoring any wine bugs of course). I will try to find it this
> weekend and put it up under my github account. for you to have a
> look at if you are interested.

That does sound interesting for additional testing.  I'd prefer that a
gcc-like wrapper not be our primary method for building to Windows
targets though - there's enough POSIX-centrism as it stands without
making further signals that Windows is a second class citizen to ccan.

> Otherwise I think rather than have the build commands in more than
> one place, the Makefile should generate wrapper scripts to call the
> compiler/linker with the correct options/paths, that ccanlint can
> use instead of directly calling the tools itself. In that case its
> just a matter of detecting windows in the Makefile which is fairly
> easy given gnu make on the windows box.

So, I'd prefer to avoid relying on gnu make on Windows if we can.
Still the basic idea sounds like it might have legs.  Need to see how
this turns out in practice.

-- 
David Gibson			| I'll have my music baroque, and my code
david AT gibson.dropbear.id.au	| minimalist, thank you.  NOT _the_ _other_
				| _way_ _around_!
http://www.ozlabs.org/~dgibson

**Comment by jgriffiths** [comment]
> I disagree :).  I think it's worth having the special case for this.

OK, I've added it in the latest push. Note that it only works if config.h is the only target on the make command line.

> I'd prefer that a gcc-like wrapper not be our primary method for building to Windows
> targets though

I agree, we need native support too.

> Need to see how this turns out in practice.

After I've found time to fix the web makefile I will probably take a look at this. Time is tight at the moment unfortunately.

**Comment by dgibson** [comment]
On Wed, Sep 21, 2016 at 12:00:13AM -0700, jgriffiths wrote:
> > I disagree :).  I think it's worth having the special case for this.
> 
> OK, I've added it in the latest push. Note that it only works if config.h is the only target on the make command line.
> 
> > I'd prefer that a gcc-like wrapper not be our primary method for building to Windows
> > targets though
> 
> I agree, we need native support too.
> 
> > Need to see how this turns out in practice.
> 
> After I've found time to fix the web makefile I will probably take a
> look at this. Time is tight at the moment unfortunately.

Isn't it always :).  Ok, well thanks for all of this.

-- 
David Gibson			| I'll have my music baroque, and my code
david AT gibson.dropbear.id.au	| minimalist, thank you.  NOT _the_ _other_
				| _way_ _around_!
http://www.ozlabs.org/~dgibson

**Comment by dgibson** [comment]
I've resolved the conflicts noted above and merged this.

There are a bunch of things that will need fixing afterwards, most notably the webpages target needs to be put back in.  Still it's a good start on improvement.

**Pull request closed without merging**
