### PR TITLE
Add xstring module - bounded string builder with three valued comparator

### PR DESCRIPTION
**Pull request by dancancode**
an old faithful bit of code, spruced up for sharing

### CODE REVIEW

**Comment by rustyrussell** [comment]
dancancode <notifications@github.com> writes:
> an old faithful bit of code, spruced up for sharing
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/rustyrussell/ccan/pull/37

This is great!

A few minor tweaks:

+	if (strcmp(argv[1], "depends") == 0) {

This can be testdepends.

/home/rusty/devel/cvs/ccan/ccan/xstring/test/run2.c:10:22: warning: no previous prototype for ‘once_only’ [-Wmissing-prototypes]
 enum failtest_result once_only(struct tlist_calls *history)

This can be static.

I'll have to add APACHE-2 to the ccanlint license tests as well, but
that's separate.

Thanks!
Rusty.

**Comment by dancancode** [comment]
Fixed.  Thanks!

**Comment by dgibson** [comment]
On Wed, Dec 09, 2015 at 11:05:20PM -0800, dancancode wrote:
> an old faithful bit of code, spruced up for sharing
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/rustyrussell/ccan/pull/37
> 
> -- Commit Summary --
> 
>   * Add xstring module - bounded string builder with three valued comparator
> 
> -- File Changes --
> 
>     M Makefile-ccan (3)
>     A ccan/xstring/LICENSE (1)
>     A ccan/xstring/_info (102)
>     A ccan/xstring/test/run.c (147)
>     A ccan/xstring/test/run2.c (38)
>     A ccan/xstring/xstring.c (207)
>     A ccan/xstring/xstring.h (236)
>     A licenses/APACHE-2 (202)
> 
> -- Patch Links --
> 
> https://github.com/rustyrussell/ccan/pull/37.patch
> https://github.com/rustyrussell/ccan/pull/37.diff
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/rustyrussell/ccan/pull/37

Sorry, took me a while to look at this.  I'm glad to see rusty merged
it already.

If you send an ssh public key we can set you up with commit access to
update this module.

I note that your commit messages don't include Signed-off-by lines.
Rusty are we encouraging these for ccan or not?


A few thoughts on xstring itself:

> When comparing two xstrings, the truncation state is taken into
account.
> If either is truncated, an equality test returns unknown (-1).

This doesn't seem quite right.  Depending on the lengths you should at
least be able to tell some cases where truncated strings can't be
equal.

Likewise you could return false for certain cases of (x contains y)
for a truncated y.

-- 
David Gibson			| I'll have my music baroque, and my code
david AT gibson.dropbear.id.au	| minimalist, thank you.  NOT _the_ _other_
				| _way_ _around_!
http://www.ozlabs.org/~dgibson

**Comment by rustyrussell** [comment]
David Gibson <notifications@github.com> writes:
> I note that your commit messages don't include Signed-off-by lines.
> Rusty are we encouraging these for ccan or not?

Encouraging, yes.  We should probably get stricter about it though.

I've added a PATCHES file to the repo with the basics.

Thanks,
Rusty.

**Comment by dancancode** [comment]
public ssh key:
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDpwtP+DsSf3isz+vWk3LioDENFTgjh9OJHP/YgiwS9BBDxcDQqX/NCw1aIEv1xwigYzeLV6PnzKWenvQzVcMQXce+jp6br1LB3IMX1b2W/Hneg6tMNng0kZnv4+k5cEVitVbdpfIjCO20kwvolEhMSN6qtSYg7NNBZH8M5nIzMhnA4Cd9IkiuI6Ps0uXeiGZau03h85CBqtCezNMdqcnuizp91JlCJCLwZYnn6TyDBM4YC6G8Tzbdz6tllpo2eB7uoEMR4UKPK/cMn3aJ9cVVQP4nWaPeGo1ZAeTlYoh8lHi1dkJYQBSXRkeaPhB18tvDi2sHE41NUJTn2n6xyPY7P dancancode@github.com

Signed-off-by: will do!

xstring false cases: Great point, I'll try to improve the code.

Thanks.  -Dan

**Comment by rustyrussell** [comment]
dancancode <notifications@github.com> writes:
> public ssh key:
> ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDpwtP+DsSf3isz+vWk3LioDENFTgjh9OJHP/YgiwS9BBDxcDQqX/NCw1aIEv1xwigYzeLV6PnzKWenvQzVcMQXce+jp6br1LB3IMX1b2W/Hneg6tMNng0kZnv4+k5cEVitVbdpfIjCO20kwvolEhMSN6qtSYg7NNBZH8M5nIzMhnA4Cd9IkiuI6Ps0uXeiGZau03h85CBqtCezNMdqcnuizp91JlCJCLwZYnn6TyDBM4YC6G8Tzbdz6tllpo2eB7uoEMR4UKPK/cMn3aJ9cVVQP4nWaPeGo1ZAeTlYoh8lHi1dkJYQBSXRkeaPhB18tvDi2sHE41NUJTn2n6xyPY7P dancancode@github.com

Done!

You can now push to 'ccan@ozlabs.org:ccan': you'll see it rebuilding the
webpages and pushing from there to github.

Thanks!
Rusty.

**Pull request closed without merging**
