### PR TITLE
Add A-star module

### PR DESCRIPTION
**Pull request by smcameron**
Signed-off-by: Stephen M. Cameron <stephenmcameron@gmail.com>

### CODE REVIEW

**Comment by rustyrussell** [comment]
Best example ever: I ran it, and even blocked off the maze to check.  Nice work!

**Comment by dgibson** [comment]
On Tue, May 03, 2016 at 02:01:18PM -0700, ccan-maintainers wrote:
> Merged #38.

Hrm, although it's nice to see the algorithm, I'm not so thrilled at
adding a hand-rolled abstract graph representation when aga / agar is
all about an abstract graph representation.

-- 
David Gibson			| I'll have my music baroque, and my code
david AT gibson.dropbear.id.au	| minimalist, thank you.  NOT _the_ _other_
				| _way_ _around_!
http://www.ozlabs.org/~dgibson

**Comment by smcameron** [comment]
Thanks, glad you liked it.

-- steve

**Comment by smcameron** [comment]
On Tue, May 3, 2016 at 2:48 PM, David Gibson <notifications@github.com>
wrote:

> On Tue, May 03, 2016 at 02:01:18PM -0700, ccan-maintainers wrote:
> > Merged #38.
>
> Hrm, although it's nice to see the algorithm, I'm not so thrilled at
> adding a hand-rolled abstract graph representation when aga / agar is
> all about an abstract graph representation.


So I looked at that briefly, and what I didn't like was that the caller
must use this struct aga_node (supposing I understood it correctly.)  The
API I came up with does not require the caller to know anything about the
graph representation, or indeed even to *have* any explicit representation
of the graph, only that the caller be able to construct little bits of the
graph (node neighbors) and even then it doesn't necessarily need to
explicitly represent any graph edges as such.   If you look at the example,
the "nodes" are to the caller just pointers to chars within a single string
that represents the entire maze -- and to the algorithm just opaque void
pointers.  It could be pointers into anything, of course, so the algorithm
doesn't care about how (or if) the caller represents the graph, and does
not make the caller transform the graph into some preferred
representation.  For this particular case of a maze represented by a single
string of ASCII chars,  forcing the algorithm user  for each character in
the string to make a struct to contain a pointer into this string, and also
a struct aga_node (for example) seemed a little too onerous.  It seemed to
me that the typical use case for A* is path finding in games.  Typically
each game will have some custom representation of terrain, dungeon, maze,
level, whatever.  Making the caller translate some native representation of
the graph into another representation that the algorithm prefers or making
them embed an algorithm specific data structure into the game's native data
structure -- esp. when the graph data structure may be a lot bigger than
the native data structure which may quite frequently be as small as 1 char
per node seemed sub optimal from a "how much friction is encountered to use
this API" standpoint.  Any implementation that forces transformation of the
graph into a particular representation generally presents so much friction
that it is usually easier to re-write the algorithm.  That was my rationale
anyhow.

I won't try to claim that my implementation's internal representation of
the graph which it builds up is anything special though.

-- steve

**Comment by dgibson** [comment]
On Tue, May 03, 2016 at 05:41:44PM -0700, smcameron wrote:
> On Tue, May 3, 2016 at 2:48 PM, David Gibson <notifications@github.com>
> wrote:
> 
> > On Tue, May 03, 2016 at 02:01:18PM -0700, ccan-maintainers wrote:
> > > Merged #38.
> >
> > Hrm, although it's nice to see the algorithm, I'm not so thrilled at
> > adding a hand-rolled abstract graph representation when aga / agar is
> > all about an abstract graph representation.
> 
> 
> So I looked at that briefly, and what I didn't like was that the caller
> must use this struct aga_node (supposing I understood it correctly.)

That's true in aga, but not in agar - that uses a void * to represent
nodes, just like your module.

The trade-off is that aga doesn't require dynamic memory allocation -
which means you need to have the aga_node structure to store per-node
information.  agar does use memory allocation, and doesn't need the
aga_node structure.

> The
> API I came up with does not require the caller to know anything about the
> graph representation, or indeed even to *have* any explicit representation
> of the graph, only that the caller be able to construct little bits of the
> graph (node neighbors) and even then it doesn't necessarily need to
> explicitly represent any graph edges as such.

That's true of aga as well.  It also uses neighbour callbacks to find
the edges from a node as needed.

> If you look at the example,
> the "nodes" are to the caller just pointers to chars within a single string
> that represents the entire maze -- and to the algorithm just opaque void
> pointers.

Yes.  You can do the same thing with agar.

> It could be pointers into anything, of course, so the algorithm
> doesn't care about how (or if) the caller represents the graph, and does
> not make the caller transform the graph into some preferred
> representation.

Yes.  Again, this is exactly the same concept as aga/agar.

> For this particular case of a maze represented by a single
> string of ASCII chars,  forcing the algorithm user  for each character in
> the string to make a struct to contain a pointer into this string, and also
> a struct aga_node (for example) seemed a little too onerous.

Right, so use agar.

> It seemed to
> me that the typical use case for A* is path finding in games.  Typically
> each game will have some custom representation of terrain, dungeon, maze,
> level, whatever.  Making the caller translate some native representation of
> the graph into another representation that the algorithm prefers

Yeah, I get it.  It's not just games, but heaps of cases where a graph
structure is implicit in existing data structures.  aga/agar exists
for exactly that reason.

> or making
> them embed an algorithm specific data structure into the game's native data
> structure

Right, there's a trade-off here.  aga means embedding the structure,
but gives you fixed memory overhead.  agar avoids that, but has less
obvious internal allocations.

> -- esp. when the graph data structure may be a lot bigger than
> the native data structure which may quite frequently be as small as 1 char
> per node seemed sub optimal from a "how much friction is encountered to use
> this API" standpoint.  Any implementation that forces transformation of the
> graph into a particular representation generally presents so much friction
> that it is usually easier to re-write the algorithm.  That was my rationale
> anyhow.

Yes... and the rationale behind agar as well.

> I won't try to claim that my implementation's internal representation of
> the graph which it builds up is anything special though.

Sure.  agar uses aga internally, essentially it uses the aga_node
structures to build an internal temporary representation, then runs
the aga algorithms on that.

-- 
David Gibson			| I'll have my music baroque, and my code
david AT gibson.dropbear.id.au	| minimalist, thank you.  NOT _the_ _other_
				| _way_ _around_!
http://www.ozlabs.org/~dgibson

**Pull request merged**
